BlogProjesi/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogProjesi.Models;
using BlogProjesi.Areas.Admin.Models;

namespace BlogProjesi.Areas.Admin.Controllers
{
    public class AdminHomeController : Controller
    {
        BlogProjesiDBEntities db = new BlogProjesiDBEntities();
        // GET: Admin/AdminHome
        [Authorize(Users = "deneme@deneme.com")]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Users = "deneme@deneme.com")]
        public ActionResult Ekle()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Ekle(BlogModel model)
        {
            /*if (ModelState.IsValid)
            {

            }*/

            Bloglar bloglar = new Bloglar();

            bloglar.BlogID = model.BlogID;
            bloglar.BlogBaslik = model.BlogBaslik;
            bloglar.BlogAltBaslik = model.BlogAltBaslik;
            bloglar.BlogIcerik = model.BlogIcerik;
            bloglar.Tarih = model.Tarih;

            db.Bloglar.Add(bloglar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Users = "deneme@deneme.com")]
        public ActionResult Listele()
        {
            var model = db.Bloglar.OrderByDescending(x => x.BlogID);
            return View(model);
        }

        [HttpGet]
        public ActionResult Duzenle(int id)
        {
            var model = db.Bloglar.Where(x => x.BlogID == id).FirstOrDefault();
            return View(model);
        }

        [HttpPost]
        public ActionResult Duzenle(Bloglar model)
        {
            /*if (ModelState.IsValid)
            {

            }*/

            var degistirilecek = db.Bloglar.Where(x => x.BlogID == model.BlogID).FirstOrDefault();

            degistirilecek.BlogID = model.BlogID;
            degistirilecek.BlogBaslik = model.BlogBaslik;
            degistirilecek.BlogAltBaslik = model.BlogAltBaslik;
            degistirilecek.BlogIcerik = model.BlogIcerik;
            degistirilecek.Tarih = model.Tarih;

            //db.Bloglar.Attach(degistirilecek);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Sil(int id)
        {

            var model = db.Bloglar.Where(x => x.BlogID == id).FirstOrDefault();
            return View(model);
        }
        [HttpPost]
        public ActionResult Sil(Bloglar model)
        {
            var silinecek = db.Bloglar.Where(o => o.BlogID == model.BlogID).FirstOrDefault();
            db.Bloglar.Remove(silinecek);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BlogProjesi/Areas/Admin/Views/AdminHome/Duzenle.cshtml
@model BlogProjesi.Bloglar

@{
    ViewBag.Title = "Duzenle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Bloglar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BlogID)


        <div class="form-group">
            @Html.LabelFor(model => model.BlogBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.BlogBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlogAltBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.BlogAltBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogAltBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlogIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.TextAreaFor(model => model.BlogIcerik, new { @class = "form-control", @rows = 10, @cols = 100 })
                @Html.ValidationMessageFor(model => model.BlogIcerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlogBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.BlogBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "Listele")
</div>

BlogProjesi/Areas/Admin/Views/AdminHome/Ekle.cshtml
@model BlogProjesi.Areas.Admin.Models.BlogModel

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Ekle", "AdminHome", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Bloglar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BlogID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.BlogID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlogBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.BlogBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlogAltBaslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.BlogAltBaslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogAltBaslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlogIcerik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.BlogIcerik, new { @class = "form-control", @rows = 10, @cols = 100 })
                @Html.ValidationMessageFor(model => model.BlogIcerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "Index")
</div>

BlogProjesi/Areas/Admin/Views/AdminHome/Index.cshtml
@model BlogProjesi.Bloglar

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

BlogProjesi/Areas/Admin/Views/AdminHome/Listele.cshtml
@model IEnumerable<BlogProjesi.Bloglar>

@{
    ViewBag.Title = "Listele";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.BlogBaslik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BlogAltBaslik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BlogIcerik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tarih)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BlogBaslik)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.BlogAltBaslik)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.BlogIcerik)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Tarih)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Duzenle", new { id = item.BlogID }) |
                @Html.ActionLink("Sil", "Sil", new { id = item.BlogID })
            </td>
        </tr>
    }

</table>

BlogProjesi/Areas/Admin/Views/AdminHome/Sil.cshtml
@model BlogProjesi.Bloglar

@{
    ViewBag.Title = "Sil";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h3>Blog silinsin mi?</h3>
<div>
    <hr />
    @using (Html.BeginForm())
    {
        <dl class="dl-horizontal">
            @Html.HiddenFor(model => model.BlogID)
            <dt>
                @Html.DisplayNameFor(model => model.BlogIcerik)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BlogIcerik)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BlogAltBaslik)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BlogAltBaslik)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BlogBaslik)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BlogBaslik)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tarih)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tarih)
            </dd>

        </dl>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" />
            @*@Html.ActionLink("Sil", "SilmeOnayi", "AdminHome", new { id=Model.blogID })*@ |
            @Html.ActionLink("Listeye Dön", "Index")
        </div>
    }
</div>